name: ' Deploy Reference Documentation'

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: read
  pages: write
  id-token: write

defaults:
  run:
    shell: pwsh

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}

jobs:
  DeployALDoc:
    runs-on: [ ubuntu-latest ]
    name: Deploy Reference Documentation
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize the workflow
        id: init
        uses: microsoft/AL-Go/Actions/WorkflowInitialize@d0a5de49086c1abf25bfc3dc4ac3e931e66f5bd4
        with:
          shell: pwsh
          eventId: "DO0097"
        
      - name: Read settings
        uses: microsoft/AL-Go/Actions/ReadSettings@d0a5de49086c1abf25bfc3dc4ac3e931e66f5bd4
        with:
          shell: pwsh

      - name: Determine Deployment Environments
        id: DetermineDeploymentEnvironments
        uses: microsoft/AL-Go/Actions/DetermineDeploymentEnvironments@d0a5de49086c1abf25bfc3dc4ac3e931e66f5bd4
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          shell: pwsh
          getEnvironments: 'github-pages'
          type: 'Publish'
            
      - name: Setup Pages
        if: steps.DetermineDeploymentEnvironments.outputs.deployALDocArtifact == 1
        uses: actions/configure-pages@v4
        
      - name: Build Reference Documentation
        uses: microsoft/AL-Go/Actions/BuildReferenceDocumentation@d0a5de49086c1abf25bfc3dc4ac3e931e66f5bd4
        with:
          shell: pwsh
          artifacts: 'latest'
        
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ".aldoc/_site/"
        
      - name: Deploy to GitHub Pages
        if: steps.DetermineDeploymentEnvironments.outputs.deployALDocArtifact == 1
        id: deployment
        uses: actions/deploy-pages@v4
